### PR TITLE
regression tests

### LINKED ISSUE #1: Regression Tests
Dear All,

Issue
This code plugin should contain tests for detecting and avoiding regressions. We should therefore add testing capabilities.

Proposed Solution
Moose offers testing capabilities which could be also used within this code plugin. The tests are usually started with a script named ./run_tests while the tests itself are located in a folder structure named test/tests/....

Jörg

### PR DESCRIPTION
**Pull request by jmeier**
This code plugin should contain tests for detecting and avoiding regressions. We should therefore add testing capabilities.

Moose offers testing capabilities which could be also used within this code plugin. The tests are usually started with a script named `./run_tests` while the tests itself are located in a folder structure named `test/tests/...`.

This PR adds this functionality

closes #1

### CODE REVIEW

**Comment by jmeier** [comment]
Dear @Kavan-Khaledi 

Unfortnately, with this code I got 2 failing tests:

- test:beam.Flac3d_Plate_Concentrated_Loads
- test:beam.Plate_Cantilever

Both failing with:
```
Time Step 0, time = 0

Time Step 1, time = 1, dt = 1
  Nonlinear solve did not converge due to DIVERGED_FNORM_NAN iterations 0
 Solve Did NOT Converge!
Aborting as solve did not converge


*** ERROR ***
The following error occurred in the TimeStepper 'ConstantDT' of type ConstantDT.

Solve failed and timestep already at or below dtmin, cannot continue!
```

**Comment by Kavan-Khaledi** [comment]
This is most likely due to the normalization error in v1, which I have fixed in this plugin. The latest shell model I sent you previously did not include this fix. I will review it and regold the failed tests later.

The same issue occurred with the Q4 element. All tests passed with our modified local coordinates, indicating that it does not affect the gold tests. However, with the modified v1, 4 tests have failed. I checked the differences in these tests, and they are very minor (on the order of 10^-5 in displacements).

**Comment by Kavan-Khaledi** [comment]
The line _v1[k] /= _v1[k].norm(); should be moved after the " if" condition. Because _v1[k].norm() is zero if the normal vector to the shell is parallel to the y axis.

**Comment by jmeier** [comment]
Great! Thats it! Now all tests are green

**Review by Kavan-Khaledi — APPROVED** [review]

**Pull request merged**
